## Shapes

In [1]:
import numpy as np


In [6]:
s = np.array(5)
s

array(5)

In [3]:
s.shape

()

In [7]:
x = s + 3
x

8

In [8]:
type(x)

numpy.int32

In [9]:
type(s)

numpy.ndarray

In [10]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [12]:
m.shape

(3, 3)

In [13]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [14]:
t.shape

(3, 3, 2, 1)

In [15]:
v = np.array([1,2,3,4])
x = v.reshape(4,1)
print(v)
x

[1 2 3 4]


array([[1],
       [2],
       [3],
       [4]])

In [23]:
a = v[None, :]
print(a)
a.shape


[[1 2 3 4]]


(1, 4)

In [24]:
a = v[:, None]
print(a)
a.shape

[[1]
 [2]
 [3]
 [4]]


(4, 1)

## Matrix Multiplication

In [25]:
m = np.array([[1,2,3],[4,5,6]])
m
# displays the following result:
# array([[1, 2, 3],
#        [4, 5, 6]])

n = m * 0.25
n
# displays the following result:
# array([[ 0.25,  0.5 ,  0.75],
#        [ 1.  ,  1.25,  1.5 ]])

m * n
# displays the following result:
# array([[ 0.25,  1.  ,  2.25],
#        [ 4.  ,  6.25,  9.  ]])

np.multiply(m, n)   # equivalent to m * n
# displays the following result:
# array([[ 0.25,  1.  ,  2.25],
#  

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [26]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a
# displays the following result:
# array([[1, 2, 3, 4],
#        [5, 6, 7, 8]])
a.shape
# displays the following result:
# (2, 4)

b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
b
# displays the following result:
# array([[ 1,  2,  3],
#        [ 4,  5,  6],
#        [ 7,  8,  9],
#        [10, 11, 12]])
b.shape
# displays the following result:
# (4, 3)

c = np.matmul(a, b)
c
# displays the following result:
# array([[ 70,  80,  90],
#        [158, 184, 210]])
c.shape
# displays the following result:
# (2, 3)

(2, 3)

In [27]:
a = np.array([[1,2],[3,4]])
a
# displays the following result:
# array([[1, 2],
#        [3, 4]])

np.dot(a,a)
# displays the following result:
# array([[ 7, 10],
#        [15, 22]])

a.dot(a)  # you can call `dot` directly on the `ndarray`
# displays the following result:
# array([[ 7, 10],
#        [15, 22]])

np.matmul(a,a)
# array([[ 7, 10],
#        [15, 22]])

array([[ 7, 10],
       [15, 22]])

## Transposes

In [28]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs
# displays the following result:
# array([[-0.27,  0.45,  0.64,  0.31]])

inputs.shape
# displays the following result:
# (1, 4)

weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

weights
# displays the following result:
# array([[ 0.02 ,  0.001, -0.03 ,  0.036],
#        [ 0.04 , -0.003,  0.025,  0.009],
#        [ 0.012, -0.045,  0.28 , -0.067]])

weights.shape
# displays the following result:
# (3, 4)

(3, 4)

In [29]:
np.matmul(inputs, weights)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [30]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

**Note**: You can multiply transposes if you sto