In [1]:
# Lesson 5 Exam

In [79]:
# Use the numpy library
import numpy as np

def prepare_inputs(inputs: list):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    # Given: input_array = None
    
    input_array = np.array(inputs)[None, :]
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    # Given: inputs_minus_min = None

    inputs_minus_min = input_array - input_array.min()

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    # Given: inputs_div_max = None

    inputs_div_max = inputs_minus_min / inputs_minus_min.max()

    # return the three arrays we've created
    # Given: return input_array, inputs_minus_min, inputs_div_max
    return input_array, inputs_minus_min, inputs_div_max
        
    
def multiply_inputs(m1: np.array, m2: np.array):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    # Given: pass
    if len(m1.shape) != 2 or len(m2.shape) != 2:
        raise ValueError('BadValue: Values need to be 2-dimensional matrices')
    m1_first = False
    if m1.shape[1] == m2.shape[0]:
        m1_first = True
    elif m2.shape[1] == m1.shape[0]:
        pass
    else:
        return False

    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    # Given: pass
    if m1_first:
        return np.matmul(m1, m2)
    return np.matmul(m2, m1)
    
    
def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    # Given: pass
    return np.array(values).mean()


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665


In [80]:
def run_test(test, value, expected):
    print(test)
    print('-' * 50)

    if (value == expected).all():
        print('pass')
    else:
        print(f'FAILED:{test}: {value} != {expected}')
    print('_' * 50 )
    
    
def test_prepare_inputs():
    # Init
    test_input = [1,2,3]
    passed = False
    func = prepare_inputs
    
    # Run
    arr, i_min, i_max = outputs =  func(test_input)
    
    # Test Schema
    print('\n')
    print('-' * 50)
    print(f'Testing `{func.__name__}` with input={test_input}')
    print(f'outputs = {outputs}')
    print('\n')
    print('_' * 50)
    
    # Test 1
    test = 'Shape Test'
    expected = np.array([[1, 2, 3]])
    run_test(test, arr, expected)
    
    # Test 2
    test = 'Minus Min Test'
    expected = np.array([[0, 1, 2]])
    run_test(test, i_min, expected)
        
    # Test 3
    test = 'Div Max Test'
    expected = np.array([[0.0, 0.5, 1.0]])
    run_test(test, i_max, expected)
        
        
def test_multiply_inputs():
    # Init
    func = multiply_inputs
    # Test Schema
    print('\n')
    print('-' * 50)
    print(f'Testing `{func.__name__}`\n')
    print('_' * 50)
    
    # Test 1
    test = 'Bad Shape Test'
    expected = 'ERROR'
    a1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
    a2 = np.array(None)
    for ta1, ta2 in zip([a1, a1, a2], [a2, a1, a2]):
        try:
            print(f'Testing {test}: with {ta1} and {ta2}')
            multiply_inputs(ta1, ta2)
        except ValueError as e:
            print(f'Sucessfully Caught "{e}"')
            
    print('Pass\n')
    print('_' * 50)
    
    # Test 2
    test = 'M1 . M2 Test'
    m1 = np.array([[1, 2, 3], 
                   [4, 5, 6]])
    m2 = np.array([[ 7, 10],
                   [ 8, 11],
                   [ 9, 12]])
    expected = np.array([[ 50,  68],
                         [122, 167]])
    value = func(m1, m2)
    run_test(test, value, expected)
    
    # Test 2
    test = 'M2 . M1 Test'
    m1 = np.array([[1, 2, 3], 
                   [4, 5, 6]])
    m2 = np.array([[ 7,  8],
                   [10, 11]])
    expected = np.array([[39, 54, 69],
                         [54, 75, 96]])
    value = func(m1, m2)
    run_test(test, value, expected)
    
def test_find_mean():
    # TODO: Return the average of the values in the given Python list
    # Given: pass
    # Init
    func = find_mean
    # Test Schema
    print('\n')
    print('-' * 50)
    print(f'Testing `{func.__name__}`\n')
    print('_' * 50)
    
    # Test 1
    test = 'Mean Test'
    arr = [1, 2, 3, 4, 5, 6]
    expected = (1+2+3+4+5+6)/6.0
    value = func(arr)
    run_test(test, value, expected)
            
test_prepare_inputs()
test_multiply_inputs()
test_find_mean()



--------------------------------------------------
Testing `prepare_inputs` with input=[1, 2, 3]
outputs = (array([[1, 2, 3]]), array([[0, 1, 2]]), array([[0. , 0.5, 1. ]]))


__________________________________________________
Shape Test
--------------------------------------------------
pass
__________________________________________________
Minus Min Test
--------------------------------------------------
pass
__________________________________________________
Div Max Test
--------------------------------------------------
pass
__________________________________________________


--------------------------------------------------
Testing `multiply_inputs`

__________________________________________________
Testing Bad Shape Test: with [[1 2 3]
 [4 5 6]
 [7 8 9]] and None
Sucessfully Caught "BadValue: Values need to be 2-dimensional matrices"
Testing Bad Shape Test: with [[1 2 3]
 [4 5 6]
 [7 8 9]] and [[1 2 3]
 [4 5 6]
 [7 8 9]]
Testing Bad Shape Test: with None and None
Sucessfull