# Project 2 - Intro to Neural Networks

In [1]:
import numpy as np

## Testing Example - Perceptron

In [6]:
w = np.array([[1.5, 1, -18]])
x = np.array([[7, 6, 1]]).T
w.dot(x)

array([[-1.5]])

## Logical Perceptrion Quiz

In [121]:
import pandas as pd

# TODO: Set weight1, weight2, and bias
weight1 = 2.5
weight2 = 2.5
bias = -2


# DON'T CHANGE ANYTHING BELOW
# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [False, False, False, True]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))


You got 2 wrong.  Keep trying!

 Input 1    Input 2    Linear Combination    Activation Output   Is Correct
       0          0                  -2.0                    0          Yes
       0          1                   0.5                    1           No
       1          0                   0.5                    1           No
       1          1                   3.0                    1          Yes


In [98]:
w = np.array([[1, 1, -2]])
y = np.array([[1, 0, 0, 1]])
x = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])
yx = np.array([[0, 0, 0],
               [0, 1, 0],
               [1, 0, 0],
               [1, 1, 1]])
# y = w.x

In [99]:
w.dot(x[3,:].T)

array([0])

In [ ]:
m1x1 + m2x2 = y - b


## Not Perceptron

In [126]:
import pandas as pd

# TODO: Set weight1, weight2, and bias
weight1 = 0.0
weight2 = -2
bias = 1


# DON'T CHANGE ANYTHING BELOW
# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [True, False, True, False]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))

Nice!  You got it all correct.

 Input 1    Input 2    Linear Combination    Activation Output   Is Correct
       0          0                   1.0                    1          Yes
       0          1                  -1.0                    0          Yes
       1          0                   1.0                    1          Yes
       1          1                  -1.0                    0          Yes


### AND

| 1 | 2 | O |
|---|---|---|
| T | T | T |
| T | F | F |
| F | T | F |
| F | F | F |

### OR
| 1 | 2 | O |
|---|---|---|
| T | T | T |
| T | F | T |
| F | T | T |
| F | F | F |



In [145]:
def f(w, x):
    return w.dot(x.T)
n= 0
w = np.array([[3, 4, -10]])
x = np.array([[1, 1, 1]])
r= 0.1
while True:
    print(f(w,x))
    if f(w, x) >= 0:
        break
    n += 1
    w = w + x*r


[[-3]]
[[-2.7]]
[[-2.4]]
[[-2.1]]
[[-1.8]]
[[-1.5]]
[[-1.2]]
[[-0.9]]
[[-0.6]]
[[-0.3]]
[[-7.10542736e-15]]
[[0.3]]


In [146]:
n

11

In [131]:
f(w, x)[0,0]

22

In [132]:
3+4-10

-3

In [135]:
x[0,2]

1

In [139]:
w

array([[  3.1,   4.1, -10.3]])

In [140]:
w.dot(x.T)

array([[38.1]])

In [142]:
w = np.array([[3, 4, -10]])
x = np.array([[1, 1, 1]])
w.dot(x.T)

array([[-3]])

In [ ]:
w + 