# Deep Learning Project 2: Lesson 1: Intro to NN

## Coding the Perceptron Algorithm

In [1]:
import pandas as pd
import numpy as np
import pathlib as pl
import matplotlib.pyplot as plt

In [2]:
f = pl.Path('assets/p2_l1_m11/data.csv')
np.random.seed(42)

df = pd.read_csv(f, header=None)
X = df.iloc[:,:2].values
y = df.iloc[:, -1].values
W = np.array(np.random.rand(2,1))
b = 1

### TO SUBMIT

In [3]:
import numpy as np

# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0]) ##FIXME it doesn't like starts - maybe a for loop like a pleb
#     return np.array([*map(stepFunction, np.matmul(X,W)+b)])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate=0.01):
    # Fill in code
    for i in range(X.shape[0]):
        alpha_i = (y[i] - prediction(X[i,:], W, b)) * learn_rate
        W[:, 0] += X[i, :] * alpha_i
        b += alpha_i
    return W, b

# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines


### OUTPUT / Experimentation

In [4]:
trainPerceptronAlgorithm(X, y)

[(array([-0.05239463]), array([-2.04919443])),
 (array([1.23772563]), array([-2.90815949])),
 (array([-39.47663703]), array([23.57864461])),
 (array([-13.13237331]), array([7.06473087])),
 (array([-9.11612538]), array([4.57527519])),
 (array([-7.79056954]), array([3.96940892])),
 (array([-6.7750263]), array([3.50523881])),
 (array([-5.97212608]), array([3.13826056])),
 (array([-5.32141098]), array([2.84084093])),
 (array([-4.78335796]), array([2.59491529])),
 (array([-4.33103935]), array([2.38817591])),
 (array([-4.09146109]), array([2.3928177])),
 (array([-3.80251597]), array([2.25914697])),
 (array([-3.54414571]), array([2.13962066])),
 (array([-3.31174122]), array([2.03210655])),
 (array([-3.10157551]), array([1.93488045])),
 (array([-2.91060228]), array([1.84653311])),
 (array([-2.73630733]), array([1.76590142])),
 (array([-2.57659722]), array([1.69201691])),
 (array([-2.4297148]), array([1.6240667])),
 (array([-2.29417429]), array([1.56136344])),
 (array([-2.16871083]), array([1.5

### Descrete vs Continuous

In [5]:
from __future__ import annotations
from functools import wraps


def wrap_score(func):
    @wraps(func)
    def score_wrap(X: 'n,2 array'):
        score = np.array([4,5]).dot(X.T) - 9
        return func(score)
    return score_wrap

# def score(X: 'n,2 array'):
#     return np.array([4,5]).dot(X.T) - 9

def sigmoid(score):
    return (1+np.exp(-score)) ** -1

@wrap_score
def my_score(X: 'n,2 array'):
    return (1+np.exp(-X)) ** -1

def softmax(L: list(int)):
    sum_e =  sum([np.exp(i) for i in L])
    return [np.exp(zi)  / sum_e for zi in L]

In [6]:
my_score(X)

array([0.0020328 , 0.00167195, 0.00153523, 0.0032615 , 0.00548455,
       0.00064314, 0.0019504 , 0.00340945, 0.00403575, 0.00109842,
       0.00025264, 0.00108674, 0.00289163, 0.00581028, 0.00694841,
       0.00182312, 0.00261146, 0.00142696, 0.00554212, 0.00326459,
       0.00469342, 0.00536489, 0.00861772, 0.00091614, 0.01288949,
       0.01303598, 0.0039543 , 0.00095297, 0.00061713, 0.00441418,
       0.00169914, 0.0007363 , 0.00454257, 0.01459218, 0.00192451,
       0.00123074, 0.01816405, 0.00569192, 0.00544401, 0.00315109,
       0.00377433, 0.0259986 , 0.00081322, 0.01437111, 0.0002509 ,
       0.00067115, 0.00676483, 0.0052026 , 0.0010781 , 0.00297367,
       0.1434655 , 0.01380545, 0.0922087 , 0.0951504 , 0.02072991,
       0.23880359, 0.11640328, 0.08270341, 0.05017742, 0.09043624,
       0.01320926, 0.10627291, 0.03776958, 0.06196311, 0.04812142,
       0.08560022, 0.02846201, 0.01456818, 0.01566604, 0.12319134,
       0.2096958 , 0.0395548 , 0.14932183, 0.04618653, 0.02725

In [7]:
my_score(np.array([(1, 1), 
                   (2, 4), 
                   (5, -5),
                   (-4, 5)]))

array([5.00000000e-01, 9.99999994e-01, 8.31528028e-07, 5.00000000e-01])

In [8]:
softmax([5,6,7])

[0.09003057317038046, 0.24472847105479764, 0.6652409557748219]

### Cross-Entropy

In [10]:
import numpy as np

def cross_entropy(Y, P):
    Y = np.array(Y)
    P = np.array(P)
    return Y.dot(-np.log(P.T))  + (1-Y).dot(-np.log((1-P).T))


def test_ce():
    Y = [0, 1, 0]
    P = [0.9, 0.2, 0.1]
    expected = -sum([np.log(0.1), np.log(0.2), np.log(0.9)])
    return expected - cross_entropy(Y, P)

test_ce()

-8.881784197001252e-16

## Module 32

In [41]:
# 0.88 = w1 * 0.4 + w2 * 0.6 + b
x = np.array([[0.4, 0.6, 1]])
# w . x = y
# w . (x.x) = (y.x)
# w . (x.x) - y.x = 0
# (w . (x) - y) = 0
# w-1.w.x = w-1.y
# I.x = w-1.y
# x = w-1.y
# need to recall multi-var...

In [50]:
def sigmoid_results(func):
    @wraps(func)
    def sigmoid(*args, **kwargs):
        returned = func(*args, **kwargs)
        return (1+np.exp(-returned)) ** -1
    return sigmoid

@sigmoid_results
def f(w1, w2, b):
    x = np.array([0.4, 0.6, 1])
    return np.array([w1,w2, b]).dot(x)


In [53]:
# Search for 88% return
[print(x) for x in map(lambda w: f(*w), [(2, 6, -2), (3, 5, -2.2), (5, 4, -3)])];

0.9168273035060777
0.8807970779778823
0.8021838885585818
